# Generated by Django 3.2.11 on 2022-01-22 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='badge',
            field=models.ImageField(blank=True, null=True, upload_to='badges/'),
        ),
    ]
