# Generated by Django 3.2.11 on 2022-02-20 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='show_dislikes',
            new_name='shows_dislikes',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='show_favorites',
            new_name='shows_favorites',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='show_likes',
            new_name='shows_likes',
        ),
    ]
