# Generated by Django 3.2.11 on 2022-01-22 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0001_initial'),
        ('users', '0002_auto_20220122_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('timestampbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='others.timestampbase')),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('others.timestampbase',),
        ),
        migrations.AddField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='_users_user_follows_+', through='users.Follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
