# Generated by Django 3.2.11 on 2022-02-28 17:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('others', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='character_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='character',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='character_favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='character',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='character_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
