# Generated by Django 3.2.11 on 2022-02-16 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0003_auto_20220216_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='extra_fields',
            new_name='extra_info',
        ),
    ]
