# Generated by Django 3.2.11 on 2022-02-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0004_rename_extra_fields_character_extra_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='total_dislikes',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='total_favorites',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='total_likes',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='total_favorites',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='total_followers',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='total_likes',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
