# Generated by Django 3.2.11 on 2022-02-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0005_auto_20220216_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactermedia',
            name='file',
            field=models.FileField(upload_to='characters/media/'),
        ),
        migrations.AlterField(
            model_name='personmedia',
            name='file',
            field=models.FileField(upload_to='people/media/'),
        ),
    ]
