# Generated by Django 3.2.11 on 2022-02-16 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0006_auto_20220216_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterVisual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='characters/visual/')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visual', to='others.character')),
            ],
            options={
                'verbose_name_plural': 'character visuals',
            },
        ),
        migrations.CreateModel(
            name='PersonVisual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='people/visual/')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visual', to='others.person')),
            ],
            options={
                'verbose_name_plural': 'people visuals',
            },
        ),
        migrations.RemoveField(
            model_name='personmedia',
            name='person',
        ),
        migrations.DeleteModel(
            name='CharacterMedia',
        ),
        migrations.DeleteModel(
            name='PersonMedia',
        ),
    ]
