# Generated by Django 3.2.11 on 2022-02-16 21:46

import dezumi.others.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0007_auto_20220216_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personvisual',
            name='file',
            field=models.FileField(upload_to=dezumi.others.helpers.upload_to_people_instance_folder),
        ),
    ]
