# Generated by Django 3.2.11 on 2022-02-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0008_alter_personvisual_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personvisual',
            name='file',
            field=models.FileField(upload_to='people/visual/'),
        ),
    ]
