# Generated by Django 3.2.11 on 2022-02-28 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShowVisual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='shows/visual/')),
            ],
            options={
                'verbose_name_plural': 'shows visuals',
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('established', models.DateField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='studio/visuals/')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('airing', models.BooleanField(default=False)),
                ('season', models.PositiveIntegerField(default=0)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('episodes', models.PositiveIntegerField(default=0)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('show_type', models.CharField(blank=True, choices=[('0', 'Serie'), ('1', 'Movie'), ('2', 'OVA'), ('3', 'ONA')], max_length=4, null=True)),
                ('total_likes', models.PositiveBigIntegerField(default=0)),
                ('total_favorites', models.PositiveBigIntegerField(default=0)),
                ('total_completed', models.PositiveBigIntegerField(default=0)),
                ('total_watching', models.PositiveBigIntegerField(default=0)),
                ('total_dropped', models.PositiveBigIntegerField(default=0)),
                ('total_plan', models.PositiveBigIntegerField(default=0)),
                ('total_reviews', models.PositiveBigIntegerField(default=0)),
                ('total_recommended', models.PositiveBigIntegerField(default=0)),
                ('total_not_recommended', models.PositiveBigIntegerField(default=0)),
                ('dezumi_score', models.FloatField(default=0)),
                ('key_art', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shows.showvisual')),
                ('studio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shows.studio')),
                ('visuals', models.ManyToManyField(related_name='visuals', to='shows.ShowVisual')),
            ],
        ),
    ]
