# Generated by Django 3.2.11 on 2022-02-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='show_type',
            field=models.CharField(blank=True, choices=[(0, 'Serie'), (1, 'Movie'), (2, 'OVA'), (2, 'ONA')], max_length=4, null=True),
        ),
        migrations.DeleteModel(
            name='ShowType',
        ),
    ]
