# Generated by Django 3.2.11 on 2022-03-01 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0002_initial'),
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='characters',
            field=models.ManyToManyField(blank=True, null=True, to='others.Character'),
        ),
    ]
