# Generated by Django 3.2.11 on 2022-03-03 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0002_initial'),
        ('shows', '0002_show_characters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='characters',
            field=models.ManyToManyField(blank=True, to='others.Character'),
        ),
        migrations.CreateModel(
            name='PersonShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=60)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='others.character')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='others.person')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.show')),
            ],
        ),
        migrations.AddField(
            model_name='show',
            name='people',
            field=models.ManyToManyField(blank=True, through='shows.PersonShow', to='others.Person'),
        ),
    ]
