# Generated by Django 3.2.11 on 2022-02-19 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_auto_20220219_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='established',
            field=models.DateField(blank=True, null=True),
        ),
    ]
