# Generated by Django 3.2.11 on 2022-02-20 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_alter_studio_established'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='show_type',
            field=models.CharField(blank=True, choices=[('0', 'Serie'), ('1', 'Movie'), ('2', 'OVA'), ('3', 'ONA')], max_length=4, null=True),
        ),
    ]
